WebBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views import static

from article.views import show_article

urlpatterns = [
    path('', show_article, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('static/<path>', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    # A simple HelloWorld test
    path('test/hello/', views.test_hello_word, name='test_hello_world'),
    path('', views.home_page, name='home'),
    path('show-article/', views.show_article, name='show_article'),
    path('show-article/<int:selected_column>/', views.show_article, name='show_article_with_column'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-collect/<int:article_id>/', views.article_collect, name='article_collect'),
    path('article-cancel-collect/<int:article_id>/', views.article_cancel_collect, name='article_cancel_collect'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/', views.user_delete, name='delete'),
    path('edit/', views.profile_edit, name='edit'),
    path('userinfo/<int:show_user_id>', views.profile_show, name='userinfo'),

]

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from article.models import ArticleStorage

# ---tips---
# 修改模型后，需要使用 python manage.py makemigrations 记录修改为一次迁移
# 再使用 python manage.py migrate 将迁移应用到数据库中
class Profile(models.Model):
    """用户扩展模型"""
    # 与User模型的数据一一对应
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 电话号码
    phone = models.CharField(max_length=20, blank=True)
    # 头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d', blank=True)
    # 简介
    bio = models.TextField(max_length=300, blank=True)
    # 作者权限
    author_permission = models.BooleanField(default=False, verbose_name='创建活动权限')
    # 评论权限
    comment_permission = models.BooleanField(default=False, verbose_name='评论权限')

    # 收藏的活动
    collected_com = models.ManyToManyField(ArticleStorage,blank=True)

    def __str__(self):
        return f'user:{self.user.username}'

userprofile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import *


# 登录表单
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from .forms import *
from .models import *


# Create your views here.


def user_login(request):
    error_msg = ""
    if request.user.is_authenticated:
        return redirect("article:show_article")
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # 取出合法数据
            data = user_login_form.cleaned_data
            # 检测是否匹配数据库中的用户
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect("article:show_article")
            else:
                error_msg = "用户名或密码错误，请重新输入！"
        else:
            error_msg = "输入格式错误，请重新输入！"
    user_login_form = UserLoginForm()
    login_context = {'login_form': user_login_form, 'error_msg': error_msg}
    return render(request, template_name='userprofile/login.html', context=login_context)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def user_register(request):
    error_msg = ""
    if request.user.is_authenticated:
        return redirect("article:show_article")
    if request.method == 'POST':
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save()
            Profile.objects.create(user=new_user)
            login(request, new_user)
            return redirect('article:show_article')
        else:
            error_msg = "用户名或密码格式有误，请重新输入！"
    user_register_form = UserRegisterForm()
    register_context = {'register_form': user_register_form, 'error_msg': error_msg}
    return render(request, template_name='userprofile/register.html', context=register_context)


@login_required
def user_delete(request):
    error_msg = ""
    delete_user = request.user
    if request.method == 'POST':
        logout(request)
        delete_user.delete()
        return redirect('article:show_article')
    delete_context = {'error_msg': error_msg}
    return render(request, template_name='userprofile/delete.html', context=delete_context)


@login_required
def profile_edit(request):
    error_msg = ""
    if Profile.objects.filter(user_id=request.user.id).exists():
        profile = Profile.objects.get(user_id=request.user.id)
    else:
        profile = Profile.objects.create(user=request.user)
    if request.method == 'POST':
        profile_form = ProfileForm(data=request.POST)
        if profile_form.is_valid():
            profile_cdata = profile_form.cleaned_data
            profile.phone = profile_cdata['phone']
            profile.bio = profile_cdata['bio']
            profile.save()
            return redirect("userprofile:userinfo", show_user_id=request.user.id)
        else:
            error_msg = "输入格式错误，请重新输入！"
    edit_context = {'profile': profile, 'error_msg': error_msg}
    return render(request, template_name='userprofile/edit.html', context=edit_context)


def profile_show(request, show_user_id):
    show_user = get_object_or_404(User, id=show_user_id)
    if Profile.objects.filter(user_id=request.user.id).exists():
        profile = Profile.objects.get(user_id=request.user.id)
    else:
        profile = Profile.objects.create(user=request.user)
    created_articles = ArticleStorage.objects.filter(author=request.user)
    collect_articles = profile.collected_com.all()
    edit_context = {'profile': profile, 'show_user': show_user,
                    'created_articles': created_articles, 'collect_articles': collect_articles}
    return render(request, template_name='userprofile/info.html', context=edit_context)

templates/userprofile/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}删除用户 - delete{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        <form
                style="display:none;"
                id="user_delete"
                action="{% url 'userprofile:delete' %}"
                method="POST"
        >
            {% csrf_token %}
            <button type="submit">send</button>
        </form>
        <div class="container">
            <div class="row">
                <h1 class="col-12 mt-4 mb-4">删除用户</h1>
                <div class="col-12">
                    <p>正在删除用户：{{ user.username }}</p><br>
                    <span style="color: #FF0000; ">用户删除后不可恢复！</span>
                    <br>
                    <input type="button" class="btn btn-primary" onclick="user_delete()" value="删除"/>
                    <input type="button" class="btn btn-primary" onclick="javascript:history.back()" value="返回"/>
                    <span style="color: #FF0000; ">{{ error_msg }}</span>
                </div>
            </div>
        </div>
        <script>
            function user_delete() {
                // 调用layer弹窗组件
                layer.open({
                    title: "删除用户",
                    content: "确认删除该用户吗？此操作不可撤销。",
                    btn: ['确认', '取消',],
                    yes: function (index, layero) {
                        $('form#user_delete button').click();
                        layer.close(index);
                    },
                    btn2: function () {
                        layer.closeAll();
                    },
                })
            }
        </script>
    {% endif %}
{% endblock content %}

templates/userprofile/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %} 编辑用户信息 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <div class="col-md-4">用户名: {{ user.username }}</div>
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- phone -->
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                    </div>
                    <!-- bio -->
                    <div class="form-group col-md-4">
                        <label for="bio">简介</label>
                        <textarea type="text" class="form-control" id="bio" name="bio"
                                  rows="12">{{ profile.bio }}</textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                    <span style="color: #FF0000; ">{{ error_msg }}</span>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/userprofile/info.html
{% extends "base.html" %}
{% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="col-12 mt-4 mb-4">个人信息</h1>

            <div class="col-12">
                {% if show_user.id == user.id %}
                    <a href="{% url 'userprofile:edit' %}" class="btn btn-primary">编辑</a>
                {% endif %}
                <br>
                <br>
                <div class="col-md-4">用户名: {{ show_user.username }}</div>
                <hr>
                <div class="col-md-4">创建活动权限: {{ profile.author_permission }}</div>
                <hr>
                <div class="col-md-4">评论权限: {{ profile.comment_permission }}</div>
                <hr>
                <div class="col-md-4">电话：{{ profile.phone }}</div>
                <hr>
                <div class="col-md-4">个人简介：</div>
                <div class="col-12">{{ profile.bio }}</div>
                <hr>
                <div class="col-md-4">我创建的活动：</div>
                <div class="row mt-2">
                    <!--列出每篇文章-->
                    {% for article in created_articles %}
                        <!-- 文章内容 -->
                        <div class="col-4 mb-4">
                            <!-- 卡片容器 -->
                            <div class="card h-100">
                                <!-- 标题 -->
                                <h4 class="card-header">{{ article.title }}</h4>
                                <!-- 概述 -->
                                <div class="card-body">
                                    <!--取出概述的前150字-->
                                    <p class="card-text">{{ article.overview|slice:'100'|safe }}...</p>
                                    <p class="card-text">{{ article.com_start_time|slice:'100' }}...</p>
                                </div>
                                <!-- 注脚 -->
                                <div class="card-footer">
                                    <a href="{% url 'article:article_detail' article.id %}"
                                       class="btn btn-primary">阅读本文</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <hr>
                <div class="col-md-4">我的收藏：</div>
                <div class="row mt-2">
                    <!--列出每篇文章-->
                    {% for article in collect_articles %}
                        <!-- 文章内容 -->
                        <div class="col-4 mb-4">
                            <!-- 卡片容器 -->
                            <div class="card h-100">
                                <!-- 标题 -->
                                <h4 class="card-header">{{ article.title }}</h4>
                                <!-- 概述 -->
                                <div class="card-body">
                                    <!--取出概述的前150字-->
                                    <p class="card-text">{{ article.overview|slice:'100'|safe }}...</p>
                                    <p class="card-text">{{ article.com_start_time|slice:'100' }}-{{ article.com_end_time|slice:'100' }}</p>
                                </div>
                                <!-- 注脚 -->
                                <div class="card-footer">
                                    <a href="{% url 'article:article_detail' article.id %}"
                                       class="btn btn-primary">阅读本文</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>


        </div>
    </div>
{% endblock content %}

templates/userprofile/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录 - login{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="col-12 mt-4 mb-4">用户登录</h1>
            <div class="col-12">
                <br>
                <form method="post" action="." style="width: 50%">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                    <span style="color: #FF0000; ">{{ error_msg }}</span>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/userprofile/register.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}注册 - register{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
        <h1 class="col-12 mt-4 mb-4">个人信息</h1>
            <div class="col-12">
                <br>
                <form method="post" action="." class="form">
                    {% csrf_token %}
                    {% bootstrap_form register_form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">注册</button>
                    {% endbuttons %}
                </form>
                <span style="color: #FF0000; ">{{ error_msg }}</span>
            </div>
        </div>
    </div>
{% endblock content %}