WebBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views import static

from article.views import show_article

urlpatterns = [
    path('', show_article, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('static/<path>', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    # A simple HelloWorld test
    path('test/hello/', views.test_hello_word, name='test_hello_world'),
    path('', views.home_page, name='home'),
    path('show-article/', views.show_article, name='show_article'),
    path('show-article/<int:selected_column>/', views.show_article, name='show_article_with_column'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-collect/<int:article_id>/', views.article_collect, name='article_collect'),
    path('article-cancel-collect/<int:article_id>/', views.article_cancel_collect, name='article_cancel_collect'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/', views.user_delete, name='delete'),
    path('edit/', views.profile_edit, name='edit'),
    path('userinfo/<int:show_user_id>', views.profile_show, name='userinfo'),

]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 8rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: lightslategrey;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <!-- 网站标题 -->
    <title>{% block title %}{% endblock %}</title>

    <!--引入bootstrap的css-->
    <!--<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <!--引入pygmentize的default.css，用于高亮代码-->
    <link rel="stylesheet" href="{% static 'highlight_css/default.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}">
    <!--可选：引入layui的CSS-->
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/layui@2.7.3/dist/css/layui.css">-->
</head>

<body>
    <!--导航栏-->
    {% include 'header.html' %}
    <!-- 预置的具体页面 -->
    <div id="wrapper">
    {% block content %}{% endblock content %}
            <div id="push"></div>
    </div>

    <!-- 页脚 -->
    {% include 'footer.html' %}
    <!-- 注入jquery.js -->
    <!--<script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <!-- CDN注入popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <!-- 注入bootstrap的js文件 -->
    <!--<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>
    <!--注入layui的js文件 -->
    <script src="https://cdn.jsdelivr.net/npm/layui@2.7.3/dist/layui.js"></script>
    {% block script %}{% endblock script %}
    {% include 'back_to_top_func.html' %}
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 80px;
        }
    </style>
</body>
</html>

templates/footer.html
{% load static %}
<!-- 页脚 -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Gaozih 2020-2022|<a href="https://github.com/Gzh0821">Github</a></p>
        <p class="m-0 text-center text-white">使用|
            <a href="https://www.djangoproject.com">Django</a> |
            <a href="https://v4.bootcss.com/">Bootstrap</a> |
            <a href="https://pandao.github.io/editor.md/">Editor.md</a> |开源项目构建</p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏logo -->
        <a class="navbar-brand" href="{% url 'home' %}">项目测试</a>

        <!-- 导航栏入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 项目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:show_article' %}">所有活动</a>
                </li>
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:article_create' %}">新建活动</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if user.is_superuser %}<a class="dropdown-item" href='/admin'>后台管理</a>{% endif %}
                            <a class="dropdown-item" href='{% url "userprofile:userinfo" user.id %}'>个人信息</a>
                            <a class="dropdown-item" href="{% url "userprofile:logout" %}">退出登录</a>
                            <a class="dropdown-item" href="{% url "userprofile:delete" %}">删除用户</a>
                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:register' %}">注册</a>
                    </li>
                    <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>

    </div>
</nav>