WebBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views import static

from article.views import show_article

urlpatterns = [
    path('', show_article, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('static/<path>', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    # A simple HelloWorld test
    path('test/hello/', views.test_hello_word, name='test_hello_world'),
    path('', views.home_page, name='home'),
    path('show-article/', views.show_article, name='show_article'),
    path('show-article/<int:selected_column>/', views.show_article, name='show_article_with_column'),
    path('article-detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('article-collect/<int:article_id>/', views.article_collect, name='article_collect'),
    path('article-cancel-collect/<int:article_id>/', views.article_cancel_collect, name='article_cancel_collect'),
    path('article-update/<int:article_id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post-comment')
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/', views.user_delete, name='delete'),
    path('edit/', views.profile_edit, name='edit'),
    path('userinfo/<int:show_user_id>', views.profile_show, name='userinfo'),

]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager

# ---tips---
# 修改模型后，需要使用 python manage.py makemigrations 记录修改为一次迁移
# 再使用 python manage.py migrate 将迁移应用到数据库中
class ArticleColumn(models.Model):
    """博客栏目分类"""
    title = models.CharField(max_length=100, blank=True, unique=True)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        """定义栏目的元数据"""
        verbose_name = '栏目'
        verbose_name_plural = '栏目'
        # 数据排序方式:created_time倒序，再以author正序
        ordering = ['title']

    def __str__(self):
        return self.title


class ArticleStorage(models.Model):
    """博客文章数据模型/库"""

    # 文章作者
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    # 文章标题
    title = models.CharField(max_length=80)
    # 文章概述
    overview = models.CharField(max_length=100, blank=True)
    # 文章正文
    text = models.TextField()
    # 文章创建时间
    created_time = models.DateTimeField(default=timezone.now)
    # 文章更新时间
    updated_time = models.DateTimeField(auto_now=True)
    # 文章是否公开
    if_publish = models.BooleanField(default=True)
    # 文章标签
    # tags = TaggableManager(blank=True)

    # 活动开始时间
    com_start_time = models.DateTimeField(default=timezone.now)
    # 活动结束时间
    com_end_time = models.DateTimeField(default=timezone.now)
    # 活动地点
    com_location = models.CharField(max_length=100, blank=True)
    # 活动限制
    com_limit = models.CharField(max_length=100, blank=True)
    # 活动是否可以组队
    com_if_group = models.BooleanField(default=False)

    # 所属栏目
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        """定义数据库模型的元数据"""
        verbose_name = '活动'
        verbose_name_plural = '活动'
        # 数据排序方式:created_time倒序，再以author正序
        ordering = ['-created_time', 'author']

    def __str__(self) -> str:
        """调用文章的str()时返回文章标题"""
        # 返回文章标题
        return str(self.title) + '@' + str(self.author)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
from django import forms
from .models import ArticleStorage


class ArticlePostForm(forms.ModelForm):
    """写文章的表单类"""

    class Meta:
        # 表明数据模型的来源
        model = ArticleStorage
        # 定义提交表单中的字段
        fields = ('title', 'overview', 'column', 'com_start_time', 'com_end_time', 'com_location', 'com_limit'
                  , 'text', 'if_publish', 'com_if_group')

article/views.py
import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import ArticlePostForm
from .models import *
from userprofile.models import Profile
from comment.models import Comment


# 主页
def home_page(request):
    return redirect("article:show_article")


def test_hello_word(request):
    """A simple HelloWorld test,return USER_AGENT for example"""
    return HttpResponse(f"[Server Start Success][user agent:{str(request.META['HTTP_USER_AGENT'])}]"
                        f"[IP address:{str(request.META['REMOTE_ADDR'])}]")


def page_not_found(request, exception):
    return render(request, '404.html', status=404, context={'exception': exception})


def show_article(request, selected_column=None):
    """展示所有发布的文章"""
    search = request.GET.get('search')
    show_collect = request.GET.get('collect')
    if request.user.is_authenticated and show_collect:
        profile = Profile.objects.get(user_id=request.user.id)
        article_list = profile.collected_com.all()
    else:
        article_list = ArticleStorage.objects.all()
    if search:
        # 进行搜索
        # article_list = ArticleStorage.objects.filter(Q(title__icontains=search) |
        #                                              Q(text__icontains=search) |
        #                                              Q(overview__icontains=search))
        article_list = article_list.filter(Q(title__icontains=search) |
                                           Q(text__icontains=search) |
                                           Q(overview__icontains=search))
    else:
        search = ''
        # article_list = ArticleStorage.objects.all()

    if selected_column:
        column = get_object_or_404(ArticleColumn, id=selected_column)
        article_list = article_list.filter(column_id=column)
    else:
        column = ArticleColumn.objects.none()

    paginator = Paginator(article_list, 6)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    all_column = ArticleColumn.objects.all()
    # 传递给模板的对象
    show_article_context = {'articles': articles, 'search': search, 'show_collect': show_collect,
                            'all_column': all_column, 'now_column': column}
    return render(request, template_name='article/list.html', context=show_article_context)


def article_detail(request, article_id):
    """获得指定id的文章"""
    error_msg = ""
    if_collected = False
    selected_article = get_object_or_404(ArticleStorage, id=article_id)
    # 该文章不可见时进行屏蔽处理
    # TODO:创建单独的屏蔽页面
    article_markdown = markdown.Markdown(
        extensions=[
            # 缩写,表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 标题扩展
            'markdown.extensions.toc',
            'markdown.extensions.nl2br'
        ])
    # 若文章未公开，显示未公开信息
    if not selected_article.if_publish:
        error_msg = '该活动未被公开'

    # 若文章已公开，显示未公开信息
    if not request.user.is_authenticated:
        permission_grade = -1
        comment_permission = False
    else:
        profile = Profile.objects.get(user_id=request.user.id)
        if_collected = profile.collected_com.filter(id=article_id).exists()
        comment_permission = profile.comment_permission
        if not profile.author_permission:
            permission_grade = 0
        else:
            permission_grade = 4 if request.user.is_superuser else (1 if selected_article.author == request.user else 0)
    # 传递给模板的对象
    if selected_article.if_publish or request.user.is_superuser or selected_article.author == request.user:
        selected_article.text = article_markdown.convert(selected_article.text)
        comments = Comment.objects.filter(article=article_id)
    else:
        selected_article.text = '该活动未被公开！'
        comments = Comment.objects.none()
    # 是否已收藏

    detail_context = {'article': selected_article,
                      'user': request.user,
                      'if_collected': if_collected,
                      'permission_grade': permission_grade,
                      'comment_permission': comment_permission,
                      'toc': article_markdown.toc,
                      'comments': comments,
                      'error_msg': error_msg}
    return render(request, template_name='article/detail.html', context=detail_context)


@login_required
def article_create(request):
    """处理文章创建"""
    error_msg = ""
    create_user = request.user
    profile = Profile.objects.get(user_id=create_user.id)
    if not profile.author_permission:
        return redirect('article:show_article')
    if request.method == 'POST':
        # 存储提交的POST数据
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的POST是否满足要求
        if article_post_form.is_valid():
            # 创建提交到数据库的对象(暂不提交)
            add_new_article = article_post_form.save(commit=False)
            # 指定提交的用户为作者
            add_new_article.author = create_user
            add_new_article.save()
            # article_post_form.save_m2m()
            return redirect(add_new_article)
        else:
            error_msg = "创建表单格式错误！"
    article_post_form = ArticlePostForm()
    columns = ArticleColumn.objects.all()
    create_context = {'article_post_form': article_post_form,
                      'error_msg': error_msg,
                      'columns': columns}
    return render(request, template_name='article/create.html', context=create_context)


@login_required
def article_delete(request, article_id):
    profile = Profile.objects.get(user_id=request.user.id)
    if request.method == 'POST' and profile.author_permission:
        select_article = get_object_or_404(ArticleStorage, id=article_id)
        if select_article.author == request.user or request.user.is_superuser:
            select_article.delete()
            return redirect('article:show_article')
    return redirect("article:article_detail", article_id=article_id)


@login_required
def article_update(request, article_id):
    error_msg = ""
    select_article = get_object_or_404(ArticleStorage, id=article_id)
    profile = Profile.objects.get(user_id=request.user.id)
    if not (profile.author_permission and (select_article.author == request.user or request.user.is_superuser)):
        return redirect("article:article_detail", article_id=article_id)
    if request.method == 'POST':
        # 存储提交的POST数据
        article_post_form = ArticlePostForm(data=request.POST, instance=select_article)
        if article_post_form.is_valid():
            article_post_form.save()
            # article_post_form.save_m2m()
            return redirect("article:article_detail", article_id=article_id)
        else:
            error_msg = "活动格式错误，请重新编辑！"
    article_post_form = ArticlePostForm()
    columns = ArticleColumn.objects.all()
    update_context = {'article': select_article,
                      'article_post_form': article_post_form,
                      'error_msg': error_msg,
                      'columns': columns}
    # 将响应返回到模板中
    return render(request, 'article/update.html', update_context)


@login_required
def article_collect(request, article_id):
    profile = Profile.objects.get(user_id=request.user.id)
    select_article = get_object_or_404(ArticleStorage, id=article_id)
    profile.collected_com.add(select_article)
    return redirect("article:article_detail", article_id=article_id)


@login_required
def article_cancel_collect(request, article_id):
    profile = Profile.objects.get(user_id=request.user.id)
    if request.method == 'POST':
        select_article = get_object_or_404(ArticleStorage, id=article_id)
        profile.collected_com.remove(select_article)
    return redirect("article:article_detail", article_id=article_id)

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ article.title }}-{{ article.author }}
{% endblock title %}

{% block content %}

    <!-- 文章详情 -->
    <div class="container">
        <div class="row">
            <!--文章部分-->
            <div class="col-9">

                <!-- 标题 -->
                <h1 class="mt-4 mb-4">{{ article.title }}</h1>
                <!-- 栏目 -->
                {% if article.column %}
                    <button type="button"
                            class="btn btn-sm mb-2 btn-warning"
                    >
                        {{ article.column }}
                    </button>
                {% endif %}
                <!-- 概述 -->
                <div class="">
                    <p>{{ article.overview }}</p>
                </div>
                <div class="alert alert-success">
                    <div>作者：{{ article.author }}</div>
                    <div>
                        {% if user.is_authenticated %}
                            {% if if_collected %}
                                已收藏
                                | <a href="javascript:void(0);" onclick="confirm_cancel_collect()">取消收藏</a>
                            {% else %}
                                <a href="{% url 'article:article_collect' article.id %}">收藏</a>
                            {% endif %}
                        {% endif %}
                        {% if permission_grade > 0 %}

                            | <a href="{% url 'article:article_update' article.id %}">编辑活动</a>
                            | <a href="javascript:void(0);" onclick="confirm_delete()">删除活动</a>

                        {% endif %}
                    </div>
                    <div><span style="color: red">{{ error_msg }}</span></div>
                </div>
                <div class="alert alert-info">
                    <div>活动地点：{{ article.com_location }}</div>
                    <div>活动时间：{{ article.com_start_time }} - {{ article.com_end_time }}</div>
                </div>
                <div class="alert alert-warning">
                    <div>是否允许组队：{{ article.com_if_group }}</div>
                    <div>活动限制：{{ article.com_limit }}</div>
                </div>
                {#<!-- 安全删除 -->#}
                <form
                        style="display:none;"
                        id="safe_delete"
                        action="{% url 'article:article_delete' article.id %}"
                        method="POST"
                >
                    {% csrf_token %}
                    <button type="submit">send</button>
                </form>
                {#<!-- 安全取消收藏 -->#}
                <form
                        style="display:none;"
                        id="safe_cancel_collect"
                        action="{% url 'article:article_cancel_collect' article.id %}"
                        method="POST"
                >
                    {% csrf_token %}
                    <button type="submit">send</button>
                </form>
                <!-- 文章正文 -->
                <div class="">
                    <p>{{ article.text|safe }}</p>
                </div>
                <hr>
                {% if comment_permission %}
                    <div>
                        <form
                                action="{% url 'comment:post-comment' article.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        发表评论：
                                    </strong>
                                </label>
                                <textarea
                                        type="text"
                                        class="form-control"
                                        id="body"
                                        name="body"
                                        rows="2"></textarea>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% elif user.is_authenticated %}
                    <br>
                    <h5 class="row justify-content-center">
                        您的账号暂无评论权限！
                    </h5>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}
                <!-- 显示评论 -->
                <h4>共有{{ comments.count }}条评论</h4>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于
                        <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
                    </p>
                    <pre style="font-family: inherit; font-size: 1em;">
{{ comment.body }}</pre>
                {% endfor %}
            </div>
            <br>
            <!--目录部分-->
            <div class="sidebar" id="sidebar">
                <div class="sidebar__inner">
                    <br>
                    <h4><strong>目录</strong></h4>
                    <hr>
                    <div>
                        {{ toc|safe }}
                    </div>
                </div>
            </div>
            <hr>
            <style>
                .sidebar {
                    will-change: min-height;
                }

                .sidebar__inner {
                    transform: translate(0, 0);
                    transform: translate3d(0, 0, 0);
                    will-change: position, transform;
                }
            </style>
            {% block script %}
                <script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
                <script type="text/javascript">
                    $('#sidebar').stickySidebar({
                        topSpacing: 20,
                        bottomSpacing: 20,
                    });
                </script>
                <script>
                    // 删除文章的函数
                    function confirm_delete() {
                        // 调用layer弹窗组件
                        layer.open({
                            // 弹窗标题
                            title: "删除活动",
                            // 正文
                            content: "是否删除活动：{{ article.title }} ？",
                            // 弹出选项
                            btn: ['确认', '取消',],
                            // 点击确定按钮后调用的回调函数
                            yes: function (index, layero) {
                                // 使JS点击不可见的按钮,执行表单的action
                                $('form#safe_delete button').click();
                                layer.close(index);
                            },
                            // 关闭窗口，并返回
                            btn2: function () {
                                layer.closeAll();
                            },
                        })
                    }

                    // 收藏文章的函数
                    function confirm_cancel_collect() {
                        // 调用layer弹窗组件
                        layer.open({
                            // 弹窗标题
                            title: "取消收藏活动",
                            // 正文
                            content: "是否取消收藏活动：{{ article.title }} ？",
                            // 弹出选项
                            btn: ['确认', '返回',],
                            // 点击确定按钮后调用的回调函数
                            yes: function (index, layero) {
                                // 使JS点击不可见的按钮,执行表单的action
                                $('form#safe_cancel_collect button').click();
                                layer.close(index);
                            },
                            // 关闭窗口，并返回
                            btn2: function () {
                                layer.closeAll();
                            },
                        })
                    }
                </script>
            {% endblock script %}
        </div>
    </div>


{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    首页
{% endblock title %}

<!--主页面-->
{% block content %}
    <div class="container">
        <br>
        <div class="row">
            <div class="col-auto mr-auto" style="width: 100%">
                <form class="form-inline d-flex align-items-center">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mr-2" name="search" placeholder="筛选活动..."
                           style="width: 80%">
                    <div class="form-check mr-2">
                        <input type="checkbox" class="form-check-input" id="collect" name="collect" value="True">
                        <label class="form-check-label" for="collect">仅查看已收藏</label>
                    </div>
                    <button type="submit" class="btn btn-primary">筛选</button>
                </form>
            </div>
        </div>
        <br>
        {% if search%}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的活动。</h4>
            {% endif %}

        {% elif not show_collect %}
            <a href="{% url "home" %}">所有分类</a>：
            {% for column in all_column %}
                <a href="{% url "article:show_article_with_column" column.id %}">
                    <button type="button"
                            class="btn btn-sm mb-2
                        {% if now_column == column %}
                            btn-success
                        {% else %}
                            btn-danger
                        {% endif %}"
                    >{{ column }}</button>
                </a>
            {% endfor %}
        {% endif %}
        <hr>
        <div class="row mt-2">
            <!--列出每篇文章-->
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-12">
                    <!-- 栏目 -->
                    {% if article.column %}
                        <button type="button"
                                class="btn btn-sm mb-2 btn-warning"
                        >
                            {{ article.column }}
                        </button>
                    {% endif %}
                    <!-- 标题 -->
                    <h4>
                        <b>
                            <a href="{% url 'article:article_detail' article.id %}"
                               style="color: black; font-size: 125%"
                            >
                                {{ article.title }}
                            </a>
                        </b>
                    </h4>
                    <!-- 概述 -->
                    <div>
                        <!--取出概述的前150字-->
                        <p style="color: gray;">{{ article.overview|slice:'100'|safe }}...</p>
                    </div>
                    <!-- 注脚 -->
                    <p>
                        <!-- 附加信息 -->
                        <span style="color: blue;">
                                {{ article.created_time|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                            </span>
                        <span style="color: darkred;">
                                {{ article.updated_time|date:'Y-m-d' }} 更新
                            </span>
                    </p>
                    <hr>
                </div>
            {% endfor %}

        </div>
        <div class="pagination row">
            <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&search={{ search }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&search={{ search }}"
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&search={{ search }}"
                   class="btn btn-secondary"
                >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&search={{ search }}"
                   class="btn btn-success"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
            </div>
        </div>
    </div>
{% endblock content %}

templates/article/list_old.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    首页
{% endblock title %}

<!--主页面-->
{% block content %}
    <div class="container">
        <br>
        <div class="row">
            <div class="col-auto mr-auto" style="width: 100%">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text"
                           class="form-control mb-2 mr-sm-2"
                           name="search"
                           placeholder="搜索文章..."
                           style="width: 100%"
                    >
                </form>
            </div>
        </div>
    <br>
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}
        <div class="row mt-2">
            <!--列出每篇文章-->
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-4 mb-4">
                    <!-- 卡片容器 -->
                    <div class="card h-100">
                        <!-- 标题 -->
                        <h4 class="card-header">{{ article.title }}</h4>
                        <!-- 概述 -->
                        <div class="card-body">
                            <!--取出概述的前150字-->
                            <p class="card-text">{{ article.overview|slice:'100'|safe }}...</p>
                        </div>
                        <!-- 注脚 -->
                        <div class="card-footer">
                            <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        <div class="pagination row">
            <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&search={{ search }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&search={{ search }}"
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&search={{ search }}"
                   class="btn btn-secondary"
                >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&search={{ search }}"
                   class="btn btn-success"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
            </div>
        </div>
    </div>
{% endblock content %}